server:
  port: 8087
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource